[build]
builder = "nixpacks"
buildCommand = "npm install --force --no-audit --no-fund"

[deploy]
startCommand = "npx prisma contract emit && npx prisma db update --db $DATABASE_URL && npm run start"
healthcheckPath = "/health"
healthcheckTimeout = 30

[[deploy.restart]]
disable = false
maxRetries = 3
